export default units = [
  {
    name: "Building A",
    numberOfRows: 1,
    units: [
      {
        id: 4,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A1",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 5,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A10",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 6,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A11",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 7,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A12",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 8,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A13",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 9,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A14",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 10,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A15",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 11,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A16",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 12,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A17",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 13,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A18",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 14,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A19",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 16,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A20",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 17,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A21",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 18,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A22",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 19,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A23",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 20,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A24",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 21,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A25",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 22,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A3",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 23,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A4",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 24,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A5",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 25,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A6",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        uid: 26,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A7",
        width: 40,
        height: 15,
        isAvailable: false,
      },
      {
        id: 27,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A8",
        width: 40,
        height: 15,
        isAvailable: true,
      },
      {
        id: 28,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A9",
        width: 40,
        height: 15,
        isAvailable: false,
      },
    ],
  },
];
