export default units = [
  {
    name: "Building A",
    numberOfRows: 1,
    units: [
      {
        id: 4,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A1",
        width: 28,
        height: 60,
        isAvailable: true,
      },
      {
        id: 5,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A10",
        width: 18,
        height: 60,
        isAvailable: false,
      },
      {
        id: 6,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A11",
        width: 18,
        height: 60,
        isAvailable: true,
      },
      {
        id: 7,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A12",
        width: 18,
        height: 60,
        isAvailable: false,
      },
      {
        id: 8,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A13",
        width: 18,
        height: 60,
        isAvailable: true,
      },
      {
        id: 9,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A14",
        width: 18,
        height: 60,
        isAvailable: false,
      },
      {
        id: 10,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A15",
        width: 18,
        height: 60,
        isAvailable: true,
      },
      {
        id: 11,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A16",
        width: 18,
        height: 60,
        isAvailable: false,
      },
      {
        id: 12,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A17",
        width: 18,
        height: 60,
        isAvailable: true,
      },
      {
        id: 13,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A18",
        width: 18,
        height: 60,
        isAvailable: false,
      },
      {
        id: 14,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A19",
        width: 24,
        height: 60,
        isAvailable: true,
      },
      {
        id: 16,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A20",
        width: 15,
        height: 60,
        isAvailable: false,
      },
      {
        id: 17,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A21",
        width: 14,
        height: 60,
        isAvailable: true,
      },
      {
        id: 18,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A22",
        width: 24,
        height: 60,
        isAvailable: false,
      },
      {
        id: 19,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A23",
        width: 24,
        height: 60,
        isAvailable: true,
      },
      {
        id: 20,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A24",
        width: 24,
        height: 60,
        isAvailable: false,
      },
      {
        id: 21,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A25",
        width: 24,
        height: 60,
        isAvailable: true,
      },
      {
        id: 22,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A3",
        width: 15,
        height: 60,
        isAvailable: false,
      },
      {
        id: 23,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A4",
        width: 15,
        height: 60,
        isAvailable: true,
      },
      {
        id: 24,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A5",
        width: 15,
        height: 60,
        isAvailable: false,
      },
      {
        id: 25,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A6",
        width: 15,
        height: 60,
        isAvailable: true,
      },
      {
        uid: 26,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A7",
        width: 15,
        height: 60,
        isAvailable: false,
      },
      {
        id: 27,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A8",
        width: 15,
        height: 60,
        isAvailable: true,
      },
      {
        id: 28,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "A9",
        width: 18,
        height: 60,
        isAvailable: false,
      },
    ],
  },

  {
    name: "Building B/C",
    numberOfRows: 2,
    units: [
      {
        id: 29,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B26",
        width: 21,
        height: 75,
        isAvailable: true,
      },
      {
        id: 30,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B27",
        width: 15,
        height: 40,
        isAvailable: false,
      },
      {
        id: 31,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B28",
        width: 15,
        height: 40,
        isAvailable: true,
      },
      {
        id: 32,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B29",
        width: 15,
        height: 40,
        isAvailable: false,
      },
      {
        id: 33,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B30",
        width: 15,
        height: 40,
        isAvailable: true,
      },
      {
        id: 34,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B31",
        width: 15,
        height: 40,
        isAvailable: false,
      },
      {
        id: 35,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B32",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 36,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B33",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 37,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B34",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 38,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B35",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 39,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B36",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 40,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B37",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 41,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B38",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 42,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B39",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 43,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B40",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 44,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B41",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 45,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B42",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 46,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B43",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 47,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B44",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 48,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B45",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 49,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B46",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 50,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B47",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 51,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B48",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 52,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B49",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 53,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B50",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 54,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B51",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 55,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B52",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 56,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B53",
        width: 14,
        height: 40,
        isAvailable: false,
      },
      {
        id: 57,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B54",
        width: 14,
        height: 40,
        isAvailable: true,
      },
      {
        id: 58,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B55",
        width: 28,
        height: 40,
        isAvailable: false,
      },
      {
        id: 87,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B84",
        width: 15,
        height: 45,
        isAvailable: true,
      },
      {
        id: 86,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B83",
        width: 15,
        height: 45,
        isAvailable: false,
      },
      {
        id: 85,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B82",
        width: 15,
        height: 45,
        isAvailable: true,
      },
      {
        id: 84,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B81",
        width: 15,
        height: 45,
        isAvailable: false,
      },
      {
        id: 83,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B80",
        width: 15,
        height: 45,
        isAvailable: true,
      },
      {
        id: 82,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B79",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 81,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B78",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 80,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B77",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 79,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B76",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 78,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B75",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 77,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B74",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 76,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B73",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 75,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B72",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 74,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B71",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 73,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B70",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 72,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B69",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 71,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B68",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 70,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B67",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 69,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B66",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 68,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B65",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 67,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B64",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 66,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B63",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 65,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B62",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 64,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B61",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 63,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B60",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 62,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B59",
        width: 14,
        height: 50,
        isAvailable: false,
      },
      {
        id: 61,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B58",
        width: 14,
        height: 50,
        isAvailable: true,
      },
      {
        id: 60,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B57",
        width: 14,
        height: 50,
        isAvailable: false,
      },

      {
        id: 59,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "B56",
        width: 28,
        height: 50,
        isAvailable: true,
      },
    ],
  },

  {
    name: "Building D",
    numberOfRows: 1,
    units: [
      {
        id: 103,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C85",
        width: 24,
        height: 60,
        isAvailable: true,
      },
      {
        id: 104,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C86",
        width: 24,
        height: 60,
        isAvailable: false,
      },
      {
        id: 105,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C87",
        width: 24,
        height: 60,
        isAvailable: true,
      },
      {
        id: 106,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C88",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 107,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C89",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 108,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C90",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 109,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C91",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 110,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C92",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 111,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C93",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 112,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C94",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 113,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C95",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 114,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C96",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 115,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C97",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 116,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C98",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 117,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C99",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 88,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C100",
        width: 15,
        height: 55,
        isAvailable: false,
      },
      {
        id: 89,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C101",
        width: 15,
        height: 55,
        isAvailable: true,
      },
      {
        id: 90,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C102",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 91,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C103",
        width: 15,
        height: 50,
        isAvailable: true,
      },
      {
        id: 92,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C104",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 93,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C105",
        width: 15,
        height: 50,
        isAvailable: true,
      },
      {
        id: 94,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C106",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 95,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C107",
        width: 15,
        height: 50,
        isAvailable: true,
      },
      {
        id: 96,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C108",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 97,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C109",
        width: 15,
        height: 50,
        isAvailable: true,
      },
      {
        id: 98,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C110",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 99,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C111",
        width: 15,
        height: 50,
        isAvailable: true,
      },
      {
        id: 100,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C112",
        width: 15,
        height: 50,
        isAvailable: false,
      },
      {
        id: 101,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C113",
        width: 15,
        height: 45,
        isAvailable: true,
      },
      {
        id: 102,
        facility: "Spring",
        storage_id: 2,
        length: 25,
        buy_price: 3000,
        unit_number: "C114",
        width: 30,
        height: 40,
        isAvailable: false,
      },
    ],
  },
];
